version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hyperapp
    versions:
    - 2.0.13
    - 2.0.14
    - 2.0.15
    - 2.0.16
    - 2.0.17
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.3
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.5
  - dependency-name: postcss-loader
    versions:
    - 5.1.0
  - dependency-name: webpack
    versions:
    - 5.22.0
    - 5.24.3
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.13
